In [ ]:
import torch

In [ ]:
# 1. Создайте случайный FloatTensor размера 3x4x5

a = torch.FloatTensor(3, 4, 5)
print(a)





tensor([[[2.5510e-36, 0.0000e+00, 2.9848e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.8788e+31, 1.7220e+22, 2.1715e-18, 4.3683e-05, 4.3445e-05],
         [6.6011e-07, 1.3295e+22, 4.1297e-05, 1.2926e-11, 2.1953e-04]],

        [[1.3543e-05, 6.5923e-10, 2.1707e-18, 4.5447e+30, 7.0062e+22],
         [2.1715e-18, 4.5447e+30, 7.0062e+22, 2.1707e-18, 1.9284e+31],
         [3.2314e-18, 1.8692e+20, 1.3226e-08, 1.2982e-11, 1.7062e-07],
         [6.7354e+22, 5.2661e-08, 1.9992e+20, 5.4363e+22, 1.0606e-08]],

        [[2.4154e-18, 3.1360e+27, 7.0800e+31, 3.1095e-18, 1.2250e+25],
         [7.0969e+22, 4.4260e+30, 7.2442e+22, 2.3086e-12, 7.2646e+22],
         [7.2250e+28, 1.5766e-19, 6.3376e-10, 2.1707e-18, 7.2128e+22],
         [2.1715e-18, 1.0372e-08, 1.0470e-11, 3.0881e-09, 2.5790e-09]]])


In [ ]:
# 2. Выведите его форму (shape)

a.shape

torch.Size([3, 4, 5])

In [ ]:
# 3. Приведите его к форме 6х10

a = a.reshape(6, 10)
print(a)
a.shape


tensor([[2.5510e-36, 0.0000e+00, 2.9848e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.8788e+31, 1.7220e+22, 2.1715e-18, 4.3683e-05, 4.3445e-05, 6.6011e-07,
         1.3295e+22, 4.1297e-05, 1.2926e-11, 2.1953e-04],
        [1.3543e-05, 6.5923e-10, 2.1707e-18, 4.5447e+30, 7.0062e+22, 2.1715e-18,
         4.5447e+30, 7.0062e+22, 2.1707e-18, 1.9284e+31],
        [3.2314e-18, 1.8692e+20, 1.3226e-08, 1.2982e-11, 1.7062e-07, 6.7354e+22,
         5.2661e-08, 1.9992e+20, 5.4363e+22, 1.0606e-08],
        [2.4154e-18, 3.1360e+27, 7.0800e+31, 3.1095e-18, 1.2250e+25, 7.0969e+22,
         4.4260e+30, 7.2442e+22, 2.3086e-12, 7.2646e+22],
        [7.2250e+28, 1.5766e-19, 6.3376e-10, 2.1707e-18, 7.2128e+22, 2.1715e-18,
         1.0372e-08, 1.0470e-11, 3.0881e-09, 2.5790e-09]])


torch.Size([6, 10])

In [ ]:
# 4. Создайте случайный IntTensor размера 10
b = torch.IntTensor(10)
b.shape

torch.Size([10])

In [ ]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

c = a * b
print(c)
type(c)
c.shape

tensor([[ 1.7417e-28,  0.0000e+00,  7.1634e-42,  0.0000e+00, -0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [        inf,  0.0000e+00,  5.2116e-17,  0.0000e+00, -4.3445e-05,
          1.1118e+01,  2.2181e+31,  7.2974e+04,  1.9768e-02,  1.8094e+05],
        [ 9.2469e+02,  0.0000e+00,  5.2098e-17,  0.0000e+00, -7.0062e+22,
          3.6574e-11,         inf,  1.2380e+32,  3.3199e-09,         inf],
        [ 2.2063e-10,  0.0000e+00,  3.1742e-07,  0.0000e+00, -1.7062e-07,
          1.1344e+30,  8.7862e+01,  3.5326e+29,  8.3141e+31,  8.7413e+00],
        [ 1.6491e-10,  0.0000e+00,  1.6992e+33,  0.0000e+00, -1.2250e+25,
          1.1953e+30,         inf,  1.2801e+32,  3.5307e-03,  5.9874e+31],
        [ 4.9329e+36,  0.0000e+00,  1.5210e-08,  0.0000e+00, -7.2128e+22,
          3.6574e-11,  1.7305e+01,  1.8501e-02,  4.7229e+00,  2.1256e+00]])


torch.Size([6, 10])

In [ ]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

c.resize_(6, 6)
z = torch.matmul(c, c)
z.shape


torch.Size([6, 6])

In [ ]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor(1.0, requires_grad=True) 
z = torch.tensor(0.5, requires_grad=True) 
t = torch.tensor(0.5, requires_grad=True)

y = x**3 + z - 75*t 

y.backward() 
x.grad 
z.grad 
t.grad


tensor(-75.)

In [ ]:
# 8. Создайте единичный тензор размера 5x6

single_tsr = torch.Tensor(5, 6).fill_(1)
print(single_tsr)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [ ]:
# 9. Переведите его в формат numpy


b = single_tsr.numpy()
single_tsr = b
print(single_tsr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
